cities=["Delhi","Mumbai","Mumbai","Melbourne","Sydney","Kolkata"]
print(cities)
# cities.append("Lucknow")
cities.insert(0,"Lucknow")
# cities.remove("Mumbai")
print(cities)
# cities.pop(3)
print(cities.index("Melbourne"))
print(cities.count("Mumbai"))
cities.sort()
print(cities)
cities.reverse()
new_cities=cities.copy()
print(cities)
print(new_cities)
updatedlist=new_cities.clear()
print(updatedlist)
# print(cities)

